# Generated by Django 4.0.1 on 2022-03-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='adress_for_shipping',
            new_name='shipping_adress',
        ),
    ]
