# Generated by Django 4.0.1 on 2022-03-25 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_rename_adress_for_shipping_customer_shipping_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='credit_card',
            field=models.CharField(blank=True, max_length=16, null=True, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
    ]
