# Generated by Django 4.0.1 on 2022-03-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0004_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(blank=True, to='store_app.Product'),
        ),
    ]
