# Generated by Django 4.0.1 on 2022-03-26 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_remove_customer_products_customerproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerproduct',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_app.customer'),
        ),
    ]
