# Generated by Django 4.0.1 on 2022-03-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_alter_customerproduct_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproduct',
            name='customer',
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='customer',
            field=models.ManyToManyField(to='store_app.Customer'),
        ),
    ]
