# Generated by Django 4.0.1 on 2022-03-26 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0008_remove_customerproduct_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproduct',
            name='customer',
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store_app.customer'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='customerproduct',
            name='product',
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='product',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='store_app.product'),
            preserve_default=False,
        ),
    ]
