# Generated by Django 4.0.1 on 2022-03-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_remove_customerproduct_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(blank=True, to='store_app.Product'),
        ),
        migrations.DeleteModel(
            name='CustomerProduct',
        ),
    ]
