# Generated by Django 4.0.1 on 2022-03-26 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0010_customer_products_delete_customerproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='products',
        ),
        migrations.CreateModel(
            name='CustomerProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_app.customer')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store_app.product')),
            ],
        ),
    ]
