# Generated by Django 4.0.1 on 2022-03-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0011_remove_customer_products_customerproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproduct',
            name='products',
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='products',
            field=models.ManyToManyField(to='store_app.Product'),
        ),
    ]
