# Generated by Django 4.0.1 on 2022-03-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_remove_customerproduct_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproduct',
            name='products',
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='products',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='store_app.product'),
            preserve_default=False,
        ),
    ]
