# Generated by Django 4.0.1 on 2022-03-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0013_remove_customerproduct_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproduct',
            name='products',
        ),
        migrations.AddField(
            model_name='customerproduct',
            name='products',
            field=models.ManyToManyField(to='store_app.Product'),
        ),
    ]
